/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Poker_Game;

import java.util.ArrayList;
import Poker_Game.PokerGame;
import Poker_Game.GameStage;
import Poker_Game.PokerCLI;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author billi
 */

public class PlayAgainMenu extends javax.swing.JFrame {

    /**
     * Creates new form PlayAgainMenu
     */
    private PokerGame game;
    private GameStage gameStage;
    
    public PlayAgainMenu(PokerGame game) {
        this.game = game;
        
        
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PlayAgainPanel1 = new javax.swing.JPanel();
        PlayAgainLabel1 = new javax.swing.JLabel();
        YesButton1 = new javax.swing.JButton();
        NoButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PlayAgainPanel1.setBackground(new java.awt.Color(204, 204, 204));

        PlayAgainLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        PlayAgainLabel1.setText("Would you like to play again?");

        YesButton1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        YesButton1.setText("Yes");
        YesButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YesButton1ActionPerformed(evt);
            }
        });

        NoButton1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        NoButton1.setText("No");
        NoButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PlayAgainPanel1Layout = new javax.swing.GroupLayout(PlayAgainPanel1);
        PlayAgainPanel1.setLayout(PlayAgainPanel1Layout);
        PlayAgainPanel1Layout.setHorizontalGroup(
            PlayAgainPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PlayAgainPanel1Layout.createSequentialGroup()
                .addGroup(PlayAgainPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PlayAgainPanel1Layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(PlayAgainLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PlayAgainPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(YesButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(NoButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        PlayAgainPanel1Layout.setVerticalGroup(
            PlayAgainPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PlayAgainPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(PlayAgainLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(PlayAgainPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(YesButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                    .addComponent(NoButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PlayAgainPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PlayAgainPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NoButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoButton1ActionPerformed
        this.dispose();  // Close the current frame
        new WelcomeMenu().setVisible(true);  // Open the welcome menu
    }//GEN-LAST:event_NoButton1ActionPerformed

    private void YesButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YesButton1ActionPerformed
        
        
        
        game.setResponse("yes");
        this.dispose();  // Close current frame
        PokerCLI pokerCLI = new PokerCLI();
        pokerCLI.start(game.getGameState().getPlayers().get(0).getName());  // Start a new round in the existing game
        
                       
    }//GEN-LAST:event_YesButton1ActionPerformed

 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton NoButton1;
    private javax.swing.JLabel PlayAgainLabel1;
    private javax.swing.JPanel PlayAgainPanel1;
    private javax.swing.JButton YesButton1;
    // End of variables declaration//GEN-END:variables
}
