package Poker_Game.Panel;

import Poker_Game.Database.FileManager;
import java.util.List;
import java.util.Set;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author billi
 */
public class ListOfUsersMenu extends javax.swing.JFrame {

    /**
     * Creates new form ListOfUsersMenu
     */
    public ListOfUsersMenu() {
        initComponents();
        displayUsernames();  // Call the method to display usernames when the form is created
    }
    
    // Method to display usernames in the ShowUsersTextPane1
    private void displayUsernames() {
        Set<String> usernames = FileManager.getSavedGameFiles(); // Get the list of usernames
        StringBuilder content = new StringBuilder();

        if (usernames.isEmpty()) {
            content.append("No users found.");
        } else {
            for (String username : usernames) {
                content.append(username).append("\n"); // Append each username to the content
            }
        }

        ShowUsersTextArea1.setText(content.toString()); // Set the content to the text pane
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ListUsersPanel1 = new javax.swing.JPanel();
        ListOfUsersLabel1 = new javax.swing.JLabel();
        EnterGameButton1 = new javax.swing.JButton();
        showUserGameLogButton2 = new javax.swing.JButton();
        ExitGameButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        ShowUsersTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ListOfUsersLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        ListOfUsersLabel1.setText("List Of Users");

        EnterGameButton1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        EnterGameButton1.setText("1. Play Game");
        EnterGameButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnterGameButton1ActionPerformed(evt);
            }
        });

        showUserGameLogButton2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        showUserGameLogButton2.setText("3. Show User Game Log");
        showUserGameLogButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showUserGameLogButton2ActionPerformed(evt);
            }
        });

        ExitGameButton3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        ExitGameButton3.setText("4. Return to Main Menu ");
        ExitGameButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitGameButton3ActionPerformed(evt);
            }
        });

        ShowUsersTextArea1.setColumns(20);
        ShowUsersTextArea1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ShowUsersTextArea1.setRows(5);
        jScrollPane2.setViewportView(ShowUsersTextArea1);

        javax.swing.GroupLayout ListUsersPanel1Layout = new javax.swing.GroupLayout(ListUsersPanel1);
        ListUsersPanel1.setLayout(ListUsersPanel1Layout);
        ListUsersPanel1Layout.setHorizontalGroup(
            ListUsersPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListUsersPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(ListUsersPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ListUsersPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(ListUsersPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ExitGameButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(showUserGameLogButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(EnterGameButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(39, 39, 39))
                    .addGroup(ListUsersPanel1Layout.createSequentialGroup()
                        .addComponent(ListOfUsersLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        ListUsersPanel1Layout.setVerticalGroup(
            ListUsersPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListUsersPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ListOfUsersLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(ListUsersPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(ListUsersPanel1Layout.createSequentialGroup()
                        .addComponent(EnterGameButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(showUserGameLogButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(ExitGameButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ListUsersPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ListUsersPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitGameButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitGameButton3ActionPerformed
        new WelcomeMenu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ExitGameButton3ActionPerformed

    private void EnterGameButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnterGameButton1ActionPerformed
        new AddPlayerNames().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_EnterGameButton1ActionPerformed

    private void showUserGameLogButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showUserGameLogButton2ActionPerformed
        new UserNameForLog().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_showUserGameLogButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListOfUsersMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListOfUsersMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListOfUsersMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListOfUsersMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        new ListOfUsersMenu().setVisible(true);
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EnterGameButton1;
    private javax.swing.JButton ExitGameButton3;
    private javax.swing.JLabel ListOfUsersLabel1;
    private javax.swing.JPanel ListUsersPanel1;
    private javax.swing.JTextArea ShowUsersTextArea1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton showUserGameLogButton2;
    // End of variables declaration//GEN-END:variables
}
